### ISSUE TITLE
Update pre-commit configs

### ISSUE THREAD

**Issue by lorenzwalthert** [mlr-org/styler.mlr#13]
To switch from the {styler} fork to {styler.mlr}, we need to change `.pre-commit.yaml` 

```yaml
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
```

With the current release of {precommit}. Later due to https://github.com/lorenzwalthert/precommit/pull/233, we'll need to add `additional_dependencies`, something along

```yaml
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.0
    hooks:
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
        additional_dependencies: 
        - mlr-org/styler.mlr
```

Probably we best wait until this is released.

Maybe (remotely) related: https://github.com/asottile/all-repos
